//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BeebEm.rc
//
#define IDK_TAB                         3
#define IDK_ESC                         4
#define IDK_1                           5
#define IDK_2                           6
#define IDK_3                           7
#define IDK_4                           8
#define IDK_5                           9
#define IDK_6                           10
#define IDK_7                           11
#define IDK_8                           12
#define IDK_9                           13
#define IDK_0                           14
#define IDK_Q                           15
#define IDK_W                           16
#define IDK_E                           17
#define IDK_R                           18
#define IDK_T                           19
#define IDK_Y                           20
#define IDK_U                           21
#define IDK_I                           22
#define IDK_O                           23
#define IDK_P                           24
#define IDK_CAPS                        27
#define IDK_A                           28
#define IDK_S                           29
#define IDK_D                           30
#define IDK_F                           31
#define IDK_G                           32
#define IDK_H                           33
#define IDK_J                           34
#define IDK_K                           35
#define IDK_L                           36
#define IDK_CTRL                        39
#define IDK_Z                           40
#define IDK_X                           41
#define IDK_C                           42
#define IDK_V                           43
#define IDK_B                           44
#define IDK_N                           45
#define IDK_M                           46
#define IDK_COMMA                       47
#define IDK_DOT                         48
#define IDK_FWDSLASH                    49
#define IDK_SHIFT_L                     50
#define IDK_LEFT                        51
#define IDK_RIGHT                       52
#define IDK_RETURN                      53
#define IDK_STAR                        54
#define IDK_DEL                         55
#define IDK_COPY                        56
#define IDK_UP                          57
#define IDK_DOWN                        58
#define IDK_SHIFT_LOCK                  59
#define IDK_F0                          63
#define IDK_F1                          64
#define IDK_F2                          65
#define IDK_F3                          66
#define IDK_F4                          67
#define IDK_F5                          68
#define IDK_F6                          69
#define IDK_F7                          70
#define IDK_F8                          71
#define IDK_F9                          72
#define IDK_SPACE                       73
#define IDK_BREAK                       74
#define IDK_SEMI_COLON                  75
#define IDK_EQUALS                      76
#define IDK_SHIFT_R                     77
#define IDK_AT                          78
#define IDK_OPEN_SQUARE                 79
#define IDK_CLOSE_SQUARE                80
#define IDK_BACKSLASH                   81
#define IDK_UNDERSCORE                  82
#define IDK_CARET                       83
#define IDR_MENU                        101
#define IDI_BEEBEM                      102
#define IDD_USERKYBRD                   103
#define IDM_ABOUT                       40001
#define IDM_DISC                        40002
#define IDM_LOADDISC0                   40002
#define IDM_EXIT                        40003
#define IDM_640X256                     40004
#define IDM_320X256                     40005
#define IDM_640X512                     40006
#define IDM_800X600                     40007
#define IDM_1024X768                    40008
#define IDM_1024X512                    40009
#define IDM_SPEEDANDFPS                 40010
#define IDM_240X192                     40011
#define IDM_160X128                     40012
#define IDM_SOUNDONOFF                  40013
#define IDM_44100KHZ                    40014
#define IDM_22050KHZ                    40015
#define IDM_11025KHZ                    40016
#define IDM_HIGHVOLUME                  40017
#define IDM_MEDIUMVOLUME                40018
#define IDM_LOWVOLUME                   40019
#define IDM_FULLVOLUME                  40021
#define IDM_ROMWRITES                   40022
#define IDM_LOADDISC1                   40023
#define IDM_REALTIME                    40024
#define IDM_50FPS                       40025
#define IDM_25FPS                       40026
#define IDM_10FPS                       40027
#define IDM_5FPS                        40028
#define IDM_1FPS                        40029
#define IDM_JOYSTICK                    40030
#define IDM_MOUSESTICK                  40031
#define IDM_HIDECURSOR                  40032
#define IDM_IGNOREILLEGALOPS            40033
#define IDM_KEYBOARDMAPPING1            40034
#define IDM_KEYBOARDMAPPING2            40035
#define IDM_3QSPEED                     40036
#define IDM_HALFSPEED                   40037
#define IDM_SAVESTATE                   40039
#define IDM_QUICKSAVE                   40040
#define IDM_QUICKLOAD                   40041
#define IDM_LOADSTATE                   40042
#define IDM_ALLOWWRITES_ROM0            40043
#define IDM_ALLOWWRITES_ROM1            40044
#define IDM_ALLOWWRITES_ROM2            40045
#define IDM_ALLOWWRITES_ROM3            40046
#define IDM_ALLOWWRITES_ROM4            40047
#define IDM_ALLOWWRITES_ROM5            40048
#define IDM_ALLOWWRITES_ROM6            40049
#define IDM_ALLOWWRITES_ROM7            40050
#define IDM_ALLOWWRITES_ROM8            40051
#define IDM_ALLOWWRITES_ROM9            40052
#define IDM_ALLOWWRITES_ROMA            40053
#define IDM_ALLOWWRITES_ROMB            40054
#define IDM_ALLOWWRITES_ROMC            40055
#define IDM_ALLOWWRITES_ROMD            40056
#define IDM_ALLOWWRITES_ROME            40057
#define IDM_ALLOWWRITES_ROMF            40058
#define IDM_ALLOWALLROMWRITES           40059
#define IDM_USERKYBDMAPPING             40060
#define IDM_DEFINEKEYMAP                40061
#define IDM_NEWDISC0                    40062
#define IDM_NEWDISC1                    40063
#define IDM_WPDISC0                     40064
#define IDM_WPDISC1                     40065
#define IDM_SAVE_PREFS                  40066

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40067
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
