# sun defs
INCLUDES = -I. -I/usr/common/lib/g++-include
DEPINCLUDES = $(INCLUDES) $(SDINCLUDES) -I/usr/common/lib/g++-include

CC = gcc263
CFLAGS = -O6 $(INCLUDES) $(SDINCLUDES) -Wall -finline-functions -DSUNOS
LINKFLAGS =
SDINCLUDES = -I..
SRCS = Err.cc
OBJS =  Err.o

.cc.o:
	$(CC) -c $(CFLAGS) $<

dagCL.a: $(OBJS)
	rm -f dagCL.a
	ar rc dagCL.a $(OBJS)

depend:
	makedepend -- $(DEPINCLUDES) -- $(SRCS)

clean:
	rm -f $(OBJS) dagCL.a

# DO NOT DELETE
# DO NOT DELETE THIS LINE -- make depend depends on it.

Err.o: ../dagCL/Err.h /usr/common/lib/g++-include/iostream.h
Err.o: /usr/common/lib/g++-include/streambuf.h
Err.o: /usr/common/lib/g++-include/libio.h /usr/include/stdlib.h
Err.o: /usr/include/sys/stdtypes.h
